<?php
	$pixel_id = $block->getPixelId();
	$event_code = $block->getEventCode();
?>

<!-- StoreSpot Facebook Integration Begin --->
<script type='text/javascript'>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
	n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
	n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
	t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
		document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '<?php echo $pixel_id ?>');
fbq('track', 'PageView');
<?php echo $event_code ?>
require(['jquery'], function($){
	$('button.tocart[data-post]').click(function() {
		const product = JSON.parse($(this).attr('data-post')).data.product
		fbq('track', 'AddToCart', {
			content_ids: ['stsp_' + product],
			content_type: 'product'
		});
	})
})
</script>

<noscript>
	<img height="1" width="1" style="display:none" alt="fbpx" src="https://www.facebook.com/tr?id=<?php echo $pixel_id ?>&ev=PageView&noscript=1"/>
</noscript>
<!-- StoreSpot Facebook Integration End --->
